### ISSUE TITLE
new_record? incorrectly reports `false` when `true`

### ISSUE THREAD

**Issue by aalvarado** [remiprev/her#276]
```
[7] pry(main)> Product.new.new_record?
=> false
```

```
[8] pry(main)> Product.new.method(:new_record?).source_location
=> ["/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/her-0.7.1/lib/her/model/attributes.rb",
 197]
```

**Comment by WizardOfOgz** [comment]
Since the Readme specifically mentions providing ["ActiveRecord-like methods"](https://github.com/remiprev/her/blob/f6ea2bc6f90ce9a4cce7ec6a97f482ca355f1183/README.md#activerecord-like-methods) I believe it is fair to expect `#new_record?` to be respond in a manner consistent with ActiveRecord models.

On a side note, I'm not a big fan of responding to _every_ method ending with `?` or `=`.
