### ISSUE TITLE
is her thread safe?

### ISSUE THREAD

**Issue by odyss009** [remiprev/her#427]
When I read the her source code, I saw suspicious part.

https://github.com/remiprev/her/blob/master/lib/her/model/relation.rb#L67
https://github.com/remiprev/her/blob/master/lib/her/model/associations.rb#L34

Is above code thread safe?

**Comment by edtjones** [comment]
Hi there

(Didn't write this code - @remiprev did)

Feels ok to me because even if it's not threadsafe it's defining associations which will be the same in all threads.

Unless I'm missing the point? Happy to review a PR if there's a better way :-)

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by odyss009** [comment]
Thanks for reply.
If I'm not wrong, associations method(https://github.com/remiprev/her/blob/master/lib/her/model/associations.rb#L34) can be accessed by another thread when model class has no associations.
But, it doesn't cause any problem because it returns always empty hash and it's not mutated.
```
class User include Her::Model
  use_api API
end

threads = []
queue = Queue.new
200.times do |n|
  threads << Thread.new do
      user = User.find(n)
      queue.push user
    end
  end
end
```
