### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by MrOutis** [remiprev/her#429]
Would be awesome to have something like `ActiveRecord::Base` [enum](https://github.com/rails/rails/blob/f2dfd5c6fdffdf65e6f07aae8e855ac802f9302f/activerecord/lib/active_record/enum.rb).
What do you think?

**Comment by edtjones** [comment]
Hi - it seems a bit data specific for a REST client in my opinion but please do elaborate / put together a PR and I will have a proper look. :-)

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by danielneis** [comment]
Hello,

I am using Her to interact with a model that uses ActiveRecord::Enum (http://api.rubyonrails.org/classes/ActiveRecord/Enum.html) and it is nice because when you have a "status" attribute and you set the statuses on the enum (lets say you have waiting and approved), you are given methods like .waiting? (returns true if status == waiting), .waiting! (sets the status to waiting) and .waiting (that returnas a collection of all records with status == waiting).

It seems that these methods (waiting?, approved?) always return false. The status method returns the correct status. It may be on the Her side or maybe on the Serialization side, I don't really know, but any help is welcome =)

**Comment by edtjones** [comment]
Hi @danielneis

Interesting. Can I see some code which shows what isn't working?

**Comment by danielneis** [comment]
Hello,

if you have something like this:

```
class CreateTests < ActiveRecord::Migration[5.0]
  def up
     create_table :tests do |t|
       t.integer :status
    end
  end
end

class Ticket < ActiveRecord::Base
  enum status: { scheduled: 0, done: 1, canceled: 2}
end

```

And on the client side you have:

```
class Test
  include Her::Model
end
```

You will have the following behaviou on the client side:

```
t = Ticket.find(2)
#<Ticket(tickets/2) status="done"  id=2 >
2.2.2 :003 > t.status
 => "done" 
2.2.2 :004 > t.done?
 => false 
2.2.2 :005 > t.scheduled?
 => false 
2.2.2 :006 > t.status == "done"
 => true 
```

**Comment by edtjones** [comment]
Hi @danielneis

Isn't it the job of the rest api to expose that? I can't think how Her could infer from an integer supplied from a remote endpoint what the enum should be. 

If I were developing the API and I couldn't return the string of the enum in the rest response, I would build an endpoint which exposed the mapping between integer and endpoint. 

Ed

**Comment by danielneis** [comment]
Hi @edtjones 

in fact, there is no route on the API endpoint for ```done?``` or other status methods.
I was trying to figure what what is happening and in fact, the "status" attribute is sent by the API as a string, the correct string, as the first example shows.
What I noticed is that looks like Her gives methods ending with "?" for all attributes, and also for any method I call that ends with "?" and does not exists, it returns false.

I could add the endpoints for those methods, or include the results on the JSON returned by the API, but it would be better if everything "just works" =)

**Comment by edtjones** [comment]
OK I understand @danielneis.

I can't see how we could infer the `done?()` method from the `"done"` string in a generic way, so I don't think this use-case will make it into the library (but PRs are most welcome if you can think of a way!). However for this example, you might be able to dynamically define a method on the instance by mutating it in an `after_find()` hook.

TOTALLY UNTESTED ;-)

```
class Test
   include Her::Model
   after_find ->(record) {
      record.send(:define_singleton_method, :"#{record.status}?", ->{record.status})
   }
end
```

Slightly crazy metaprogramming there, but that would define an instance method called `done?` on your instance `record`.

May / may not be what you're looking for :-)

**Comment by danielneis** [comment]
Hello!

Thank you for you clarifications.
After thinking about the problem for a while and looking at what you suggested, I think it's better for the API to send the methods ending in ```?``` because it has a way to determine which statuses are available. The methods ending in ```!``` may be called as extra calls on the API because they change the object status.

In the API side I can tell the "as_json" method to include the methods I want with something like this:

```
def Test
  def as_json(options={})
    super(options.merge({:methods => Ticket.statuses.map { |s,v| s.to_s + '?'} }))
  end 
end
```

With this I get a json attribute for each status and can use it on the Her side. =)

Best regards,
Daniel

**Comment by edtjones** [comment]
If you have total control over the API side, and no external requirements for the schema, I agree - make it as easy as possible to consume :)
