### ISSUE TITLE
Add type coercion for attributes

### ISSUE THREAD

**Issue by pablocrivella** [remiprev/her#465]
It would be really useful to add type coercion maybe using the [Dry Types](https://github.com/dry-rb/dry-types) gem

**Comment by zacharywelch** [comment]
Hi @pablocrivella, I'm a fan of the idea 😎 Something using or resembling Rails [attributes api](https://api.rubyonrails.org/v5.2.2/classes/ActiveRecord/Attributes/ClassMethods.html) is being discussed but this would require a modest overhaul of Her attributes and most likely a major release. Going to close this for now since it's out of scope.
