### ISSUE TITLE
Her::Model is incompatible with ActiveModelSerializers::Model

### ISSUE THREAD

**Issue by pablocrivella** [remiprev/her#477]
Currently this two conflict with each other, wich makes it harder to serialize "her models" with AMS.

```ruby
class Base < ActiveModelSerializers::Model
  include Her::Model

  include_root_in_json true
  parse_root_in_json true, format: :active_model_serializers
end
```

**Comment by zacharywelch** [comment]
Her [support](https://github.com/remiprev/her#activemodelserializers-support) for `ActiveModel::Serializers` only extends to parsing and consumption of APIs following the serializer format. As you pointed out the two conflict with each other because they share a similar public API (e.g. `attributes` and `associations`). Gonna close this since it's outside the scope of Her but let us know if you were able to find a solution. Thanks!
