### ISSUE TITLE
Orm#destroy fails if an attribute "attributes" is present

### ISSUE THREAD

**Issue by voltechs** [remiprev/her#486]
Similar to https://github.com/remiprev/her/issues/371, `#destroy` fails when `attributes` attribute is present. Tracked it down to this section of code. I've resorted to stripping out the `attributes` attribute from the response.

```ruby
      # lib/her/model/path.rb:18
      def request_path(params = {})
        self.class.build_request_path(params.merge(attributes.dup))
      end
```

**Comment by edtjones** [comment]
Hi @voltechs - if I understand the issues correctly, this might be a tricky fix in Her because the attributes method is defined in an activesupport mixin. 

I have successfully worked around attributes called ‘attributes’ in a middleware. 

Have a look at https://github.com/errorstudio/spektrix-ruby/blob/master/lib/spektrix/response_parser.rb - it’s pretty involved because I’m parsing some totally non-RESTful endpoints but you’ll see that there’s a comment explaining how we iterate over the data and change ‘attributes’ to ‘custom_attributes’ be for Her sees it. 

Any use?

**Comment by voltechs** [comment]
Yea that makes sense. I appreciate this! Cheers 🍻
